import oracledb

DB_USER = "system"
DB_PASSWORD = "itsrickjonas"
DB_DSN = "localhost:1521/XEPDB1"

def get_connection():
    """Returns a connection to the Oracle Database."""
    return oracledb.connect(user=DB_USER, password=DB_PASSWORD, dsn=DB_DSN)

def init_db():
    connection = get_connection()
    cursor = connection.cursor()

    # 1. CUSTOMERS Table
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMERS (
                customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                email VARCHAR2(100) UNIQUE NOT NULL
            )';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    # 2. PRODUCTS Table
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE PRODUCTS (
                product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                price NUMBER(10, 2) NOT NULL,
                stock_quantity NUMBER DEFAULT 0
            )';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    # 3. ORDERS Table (Links CUSTOMERS and PRODUCTS)
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE ORDERS (
                order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id NUMBER REFERENCES CUSTOMERS(customer_id),
                product_id NUMBER REFERENCES PRODUCTS(product_id),
                quantity NUMBER NOT NULL,
                order_date DATE DEFAULT SYSDATE
            )';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    connection.commit()
    cursor.close()
    connection.close()

if __name__ == "__main__":
    init_db()
    print("Database initialized with 3 linked tables!")