import os
import oracledb

DB_USER = os.getenv("DB_USER", "system")
DB_PASSWORD = os.getenv("DB_PASSWORD", "itsrickjonas")
DB_DSN = os.getenv("DB_DSN", "localhost:1521/XEPDB1")

def get_connection():
    try:
        connection = oracledb.connect(
            user=DB_USER, password=DB_PASSWORD, dsn=DB_DSN
        )
        return connection
    except oracledb.Error as e:
        print(f"Database connection error: {e}")
        return None

def init_db():
    conn = get_connection()
    if not conn:
        print("Failed to connect to the database. Skipping table creation.")
        return

    cursor = conn.cursor()

    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE products (
                    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100) NOT NULL,
                    category VARCHAR2(50),
                    price NUMBER(10, 2) NOT NULL,
                    stock_quantity NUMBER DEFAULT 0 NOT NULL
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE orders (
                    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_name VARCHAR2(100) NOT NULL,
                    product_id NUMBER REFERENCES products(product_id),
                    quantity NUMBER NOT NULL,
                    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    conn.commit()
    cursor.close()
    conn.close()
    print("Database tables verified/created successfully.")

if __name__ == "__main__":
    init_db()