CREATE TABLE CUSTOMERS (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0
);

CREATE TABLE ORDERS (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES CUSTOMERS(customer_id),
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    quantity NUMBER NOT NULL,
    order_date DATE DEFAULT SYSDATE
);

SELECT c.name AS customer_name, p.name AS product_name, o.quantity, (o.quantity * p.price) AS total_amount
FROM ORDERS o
JOIN CUSTOMERS c ON o.customer_id = c.customer_id
JOIN PRODUCTS p ON o.product_id = p.product_id;